In [1]:
import torch

In [2]:
some_one = torch.ones(2,2)
print(some_one)

tensor([[1., 1.],
        [1., 1.]])


In [3]:
some_zeros = torch.zeros(3,3)
print(some_zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [4]:
some_random = torch.randn(3,3)
print(some_random)

tensor([[-0.4969,  0.3859,  1.4516],
        [ 1.2293,  0.9433, -0.6529],
        [ 0.0773, -0.0822, -0.8909]])


In [5]:
a = torch.randn(5,5)
b = torch.randn(5,5)
print(a)
print(b)

tensor([[-1.2644,  0.6289,  0.4002, -1.0744,  0.5830],
        [ 0.3551, -0.9556, -1.0571,  0.6950, -1.2480],
        [ 1.1030, -1.1168,  0.8323,  1.2269,  0.2556],
        [-1.0257, -0.6912, -1.1880, -1.0696, -0.0116],
        [ 0.0439, -2.0593,  1.0130, -0.2500, -0.2282]])
tensor([[-0.2942,  0.0460,  0.2588, -0.7562,  0.0379],
        [-1.1652,  1.4714, -0.0521, -0.9417,  1.1181],
        [-0.4171, -0.0676, -1.1515,  1.1486, -2.4039],
        [ 0.0240, -0.8069,  0.9120, -0.5027,  0.7521],
        [-0.4988, -2.5618, -2.0757, -1.1351,  1.0635]])


In [6]:
a*b

tensor([[ 0.3720,  0.0289,  0.1036,  0.8124,  0.0221],
        [-0.4137, -1.4062,  0.0550, -0.6545, -1.3954],
        [-0.4601,  0.0755, -0.9585,  1.4092, -0.6145],
        [-0.0246,  0.5577, -1.0834,  0.5377, -0.0088],
        [-0.0219,  5.2756, -2.1028,  0.2838, -0.2427]])

In [7]:
c = a.mm(b)
print(c)

tensor([[-0.8443,  0.2134, -3.0109,  0.7019, -0.4949],
        [ 2.0891,  1.3179,  4.5833,  0.4845,  0.6817],
        [ 0.5316, -3.2936, -0.0266,  0.2668, -2.0131],
        [ 1.5828, -0.0911,  0.1872,  0.6129,  1.2273],
        [ 2.0718, -2.3103, -0.8023,  3.4544, -5.1668]])
